### ISSUE TITLE
元画像によってはうまくいかないことがある？

### ISSUE THREAD

**Issue by snagahiro** [rnanba/GalaxyAnnotator#12]
wcs.fitsを得た元画像によって、votable.xmlを得る時に

WARNING: FITSFixedWarning: The WCS transformation has more axes (2) than the image it is associated with (0) [astropy.wcs.wcs]

と警告が出て、 leda-votable-to-galaxy.pyの実行時にエラーがでて上手くいかないことがありました、

**Comment by rnanba** [comment]
fits を読む処理で警告ということは上手くいかないのは leda-get-votable.py の方でしょうか。こちらでは出たことのない現象でちょっと原因が思いつきません。可能なら引数で渡したファイル一式を送っていただけないでしょうか。
ただし今月いっぱいは時間がとれなさそうなので調査はだいぶ先になりそうです…

**Comment by rnanba** [comment]
お返事遅くなって申し訳ありません。調査したところ、どうやら HyperLeda のデータで視線速度(v)がマイナスの銀河でエラーになっていました。

```
    exp = math.ceil(math.log10(d_ly) - args.distance_precision)
                    ^^^^^^^^^^^^^^^^
ValueError: math domain error
```


視線速度がマイナスの銀河は大抵近くの銀河で距離が測定済みで mod0 (光度距離)がデータに入っているので赤方偏移から距離を計算する処理に入らないのですが、mod0 はないけど v に負の値が入っている銀河があって、そこで負の赤方偏移の log を計算しようとしてエラーになっていました。

こういう銀河のデータからは距離は計算できないので、-d オプションが指定されている場合、デフォルトではエラーにして、-i オプションを指定した場合には距離を計算せずに先に進むように修正します。

**Comment by rnanba** [comment]
> -d オプションが指定されている場合、デフォルトではエラーにして、-i オプションを指定した場合には距離を計算せずに先に進むように修正します。

ここはちょっと考え直しました。-i オプションは -m オプション指定時の等級不明な銀河の扱いを制御するオプションで、これを本件エラーの抑制と兼用するのは使いにくくなるので、エラーにはせず、警告をコンソール(標準エラー出力)に出力し、desc は出力しないという動作にします。

オプションで --show-negative-redshift を指定すると z 値を desc に出力するようにしますので、警告を見て気になったらこれを指定してどの銀河がそれか確認できるようにします。
